title: "PW2"

remote_theme: alexander-heimbuch/millidocs

search_tokenizer_separator: /[\s/]+/

footer_content: "Copyright &copy; 2020 Rodrigo Prestes Machado, distributed under Apache 2.0 license."

aux_links:
  "Rodrigo Prestes Machado":
    - "http://www.inf.poa.ifrs.edu.br/~rodrigo"